### ISSUE TITLE
ORG_VM's source file not totally equal with ORG_VM.qcow2 

### ISSUE THREAD

**Issue by ReyRen** [zzhou1/virt-dup#3]
@zzhou1 In some cases, ${ORG_VM} not totally using XXX/${ORG_VM}.qcow2 as the source file. For example, I'm gonna install a VM is sles15, but there is no operating system named sles15, only the sle15. After installing that, I changed the name because I really want to use sles15 as the VM name and I think the VM name can be changed casually. 
According to the above, `sudo ./virt-dup.sh -o sles15vm1 -n sles15vm2 --debug` would get 
```
/tmp/sles15vm1_dup_10148.xml is under processing for sles15vm2 
  <name>sles15vm1</name>
  <uuid>e65d76da-83bc-4cdb-baf5-c011c0d745b5</uuid>
      <mac address='52:54:00:44:0a:e0'/>
Stop, no result when search sles15vm1 in all image names
```
So, I propose the ${ORG_VM} as the source file name from named VM xml. 

If there are some misunderstanding and mistakes I made, really appreciate to let me know.

Sincerely,
Yuan

**Comment by zzhou1** [comment]
The tool distinguish VM name and IMG names. If IMG name doesn't contains VM name, it will be shared among VMs intentionally. Now this tool is completely rewirtten with python.
